nidm/experiment/tools/BIDSMRI2NIDM.py

without forcing export of a file.

RF: make BIDS to NIDM conversion more easily usable from Python

---

nidm/experiment/tools/click_main.py

fixing syntax error

---

nidm/experiment/Query.py
nidm/experiment/tests/test_query.py

and associated test case in test_query.py

Added GetProjectInstruments query to Query.py 

---

nidm/experiment/AssessmentObject.py
nidm/experiment/Query.py
nidm/experiment/Utils.py
nidm/experiment/tests/test_load_nidmowl.py
nidm/experiment/tests/test_query.py

Also added additional optional parameter to AssessmentObject constructor for specifying which assessment one is storing/describing data for.

 Test add for loading NIDM-Experiment OWL files from nidm-specs repo

---

nidm/core/Constants.py
nidm/experiment/Utils.py
nidm/experiment/tools/BIDSMRI2NIDM.py
nidm/experiment/tools/CSV2NIDM.py
nidm/experiment/tools/repronim_simple2_brainvolumes.py

Updated to support pybids 0.8.0

updated BIDSMRI2NIDM.py

---

nidm/experiment/Query.py
nidm/experiment/tests/test_query.py

Age, hand, gender now optional in SPARQL query
Updated meta data query to work with patched ABIDE graph structure.
Mark the test on a real ABIDE file as skipped b/c it is an outside dependency.

Improved extractProjectSummary to be more resilient to graph changes

---

nidm/version.py

attach @tgbugs version of rdflib

add neurdflib

---

docker/Dockerfile
docker/rundocker.sh
nidm/experiment/Query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py

Also updated project rest CLI to work with better IDs

Added "subjects" CLI interface and REST API endpoint

---

nidm/experiment/tools/BIDSMRI2NIDM.py

This pull request is opened following the one in dbkeator/PyNIDM repository.

WIP:  bidsmri2nidm with additionnal attributes 

---

docker/Dockerfile
docker/rundocker.sh

Adding apache Jenna and pynidm install
Also improved formatting to minimize docker snapshots

Improving Dockerfile

---

README.rst
docker/Dockerfile
nidm/experiment/Query.py
nidm/experiment/tests/test_query.py
nidm/experiment/tools/nidm_query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py

Also adding optional graph parse cacheing

Adding Stats Collections to the subject results on CLI/REST API

---

docs/REST_API_definition.openapi.yaml
docs/source/index.rst

Adding REST API info to the "Read the Docs" index.rst file.
Added a copy of the OpenAPI specification for the REST API.

API and command line documentation updates

---

nidm/version.py

Reverts incf-nidash/PyNIDM#196

Revert "increased version for pypi release"

---

docker/Dockerfile
nidm/experiment/Utils.py
nidm/version.py

Reverts incf-nidash/PyNIDM#213

Revert "use rapidfuzz instead of fuzzywuzzy"

---

docker/Dockerfile
nidm/experiment/Navigate.py
nidm/experiment/Query.py
nidm/experiment/tests/test_navigate.py
nidm/experiment/tests/test_query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py

* Using DataElement info when gathering instrument data
* Adding subject ID into the project summary field table
* Adding in memory caching to Navigate class
* Changing signature for navigate functions to require tuples
* Show derivative data elements in the project summary list

Improved DataElement Handling

---

nidm/experiment/Query.py
nidm/experiment/Utils.py
nidm/experiment/tools/bidsmri2nidm.py
nidm/version.py

Updated to use pybids 0.12.0 and changes needed to 'extension' parameter to pybids.get functions
Added check to make sure loaded JSON mapping files are valid JSON else error out
Updated micro version number

updated pybids.get calls to use keyword 'extension' 

---

nidm/experiment/Utils.py
nidm/version.py

added function to create DataElement UUIDs from a hash of many of the properties...prevents same UUIDs from being generated for DataElements with different properties

added function to create DataElement UUIDs from a hash of many of the properties

---

docker/Dockerfile
docker/build.sh
nidm/experiment/Query.py
nidm/experiment/tests/test_query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py

Fixes performance issue with project statistics

Rewrote the project statistics functions to improve performance.

---

nidm/experiment/Query.py
nidm/experiment/Utils.py
nidm/experiment/tools/nidm2bids.py
nidm/version.py

was reading multiple rdf:type's as literals instead of urirefs

bug fix with read_nidm function

---

docker/Dockerfile
docs/source/index.rst
nidm/experiment/Query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py
nidm/version.py

* Show the isAbout column in the /dataelements API route
* Adding the fields option to the /projects API route
* Adding isAbout to the CLI output for derivitive details

isAbout workflow improvements

---

nidm/experiment/Query.py
nidm/experiment/tests/test_navigate.py
nidm/experiment/tests/test_query.py
nidm/experiment/tools/rest.py
nidm/experiment/tools/tests/test_rest.py
nidm/experiment/tools/tests/test_rest_dataelements.py
nidm/experiment/tools/tests/test_rest_statistics.py
nidm/experiment/tools/tests/test_rest_subjects.py

Updated tests and Query.py function to accommodate new property string sourceVariable which used to be source_variable.  Made things backwards compatible

bug update to accomodate new NIDM property sourceVariable changed from source_variable

---

README.rst
nidm/experiment/tools/nidm_linreg.py
nidm/version.py

Fixes to nidm_linreg.py to prevent auto-installation of packages, additions to version.py placing required sklearn, statsmodels, and statistics packages in requirements, and fixes to README.rst to provide better instructions on how to install Homebrew and miniconda, create an environment, and install the necessary packages.

Changes to README and nidm_linreg

---

.codespellrc
nidm/experiment/tools/nidm_gmm.py
nidm/experiment/tools/nidm_kmeans.py
nidm/experiment/tools/nidm_linreg.py

The past tense and past participle of "split" are both "split".

"Splitted" is not a word

---

.github/workflows/pythontest.yml

Run tests in CI on pushes & merges to master

---

docker/rest-blaze.py
rest-server.py
setup.cfg
src/nidm/experiment/tools/rest.py

Replace simplejson with stdlib json

---

src/nidm/experiment/README.md
src/nidm/experiment/__init__.py
src/nidm/terms/README.md
src/nidm/terms/__init__.py
src/nidm/workflows/README.md
src/nidm/workflows/__init__.py

Prune `README.md` files from code directories

---

src/nidm/core/Constants.py
src/nidm/core/dot.py
src/nidm/core/provone.py
src/nidm/core/serializers/provonerdf.py

Remove uses of `six`

---

.github/workflows/pythontest.yml
setup.cfg
tox.ini

Add testing via tox

---

src/nidm/experiment/CDE.py
src/nidm/experiment/Query.py
src/nidm/experiment/Utils.py
src/nidm/experiment/tools/bidsmri2nidm.py
src/nidm/experiment/tools/nidm2bids.py
src/nidm/experiment/tools/nidm_affinity_propagation.py
src/nidm/experiment/tools/nidm_agglomerative_clustering.py
src/nidm/experiment/tools/nidm_gmm.py
src/nidm/experiment/tools/nidm_kmeans.py
src/nidm/experiment/tools/nidm_linreg.py
tox.ini

Make pytest error on warnings

---

tests/core/test_provone.py
tests/experiment/conftest.py
tests/experiment/test_experiment.py
tests/experiment/test_experiment_basic.py
tests/experiment/test_map_vars_to_terms.py
tests/experiment/test_navigate.py
tests/experiment/test_query.py
tests/experiment/tools/test_nidm_lingreg.py
tests/experiment/tools/test_rest.py
tests/experiment/tools/test_rest_dataelements.py
tests/experiment/tools/test_rest_statistics.py
tests/experiment/tools/test_rest_subjects.py

Write test temp files to temp directories

---

.github/dependabot.yml
.github/workflows/pythontest.yml

Update workflow actions versions and keep them up to date with Dependabot

---

.github/workflows/pythontest.yml

ref: https://github.com/incf-nidash/PyNIDM/issues/325#issuecomment-1534993626

Do not try to upload nonexisting junit artifacts

---

src/nidm/experiment/tools/nidm_affinity_propagation.py
src/nidm/experiment/tools/nidm_agglomerative_clustering.py
src/nidm/experiment/tools/nidm_gmm.py
src/nidm/experiment/tools/nidm_kmeans.py
src/nidm/experiment/tools/nidm_linreg.py
src/nidm/experiment/tools/utils.py
tests/experiment/tools/test_nidm_lingreg.py

@yarikoptic Here's your release PR.

Refactor printing the same text to both stdout and a file

---

src/nidm/core/BIDS_Constants.py
src/nidm/experiment/Project.py
src/nidm/experiment/tools/bidsmri2nidm.py

These changes are to support BIDS dataset conversions and adding metadata about BIDS dataset to a prov:collection, moving that metadata out of the project activity.  Effected tool: bidsmri2nidm.py

updated nidm model to collections of entities

---

src/nidm/experiment/Utils.py

PS didn't check/no test -- shouldwork™

Make key_exists more "pythonic", but it is not used at all -- remove?

---

setup.cfg
src/nidm/experiment/Acquisition.py
src/nidm/experiment/AcquisitionObject.py
src/nidm/experiment/Core.py
src/nidm/experiment/DataElement.py
src/nidm/experiment/Derivative.py
src/nidm/experiment/DerivativeObject.py
src/nidm/experiment/Navigate.py
src/nidm/experiment/Project.py
src/nidm/experiment/Query.py
src/nidm/experiment/Utils.py
src/nidm/experiment/tools/csv2nidm.py
tests/experiment/test_navigate.py

Added derivatives support to csv2nidm, included nidm:DerivativeCollection type to support queries with unknown derivatives / namespaces
Improved pynidm query -de which now returns all properties for data elements

updating for supporting derivatives with csv2nidm
