incf-nidash/PyNIDM

nidm/core/tests/test_provone.py, nidm/experiment/tests/test_experiment.py
I'm skipping tests for provone since importing `nidm.core.provone` is still breaking  `experiment`, and I wanted to have `test_experiment.py` running again.
Please see #83
cc: @sanuann ,  @satra
=> removing tests for provone 

nidm/experiment/tools/nidm_query.py, setup.py
* I added the execution of `query` command, so you can call `python nidm_query.py -nl .. -q ..`.
(there is also option of calling `query.callback()`, but then you have to provide all arguments in `callback`.)
* changing command name to `nidm`
=> calling query command in nidm_query

nidm/core/Constants.py, nidm/experiment/Query.py, nidm/experiment/tests/test_query.py
**Summary:**
GetProjectMetadata returns any project properties coded into a NIDM file
GetProjectComputedMetadata returns everything from GetProjectMetadata
plus some computed values: number of subjects and age range of subjects.
More computed values can be added at a later time.
**Questions / Issues:**
- The keys used in the JSON return strings use the 'prefixed' version of the predicate, for example: "dct:description" Is that how we want to index the JSON results? My only concern is that the prefixes might not be well defined at the other end of the REST API call. Should we ship a dictionary of prefixes along with the JSON? (or maybe make that a separate API call?)
- I added Constant values for a number of additional Project level predicates (if that is the right term) that were part of …
=> Implemented GetProjectMetadata and GetProjectComputedMetadataa

README.rst
I just came across a mismatch in capitalization between the command line entry points and the example command line calls in the README. This small PR adjusts the commands from lower-case to upper-case.
=> Capitalize commands in README

nidm/experiment/Query.py, nidm/experiment/tests/test_query.py, nidm/experiment/tools/nidm_query.py, nidm/experiment/tools/rest.py, nidm/experiment/tools/tests/test_rest.py
Added /projects and /projects/#PID routers
Show all project meta data when project details CLI rest call is made
Added non-json output for lists and dictionaries in the CLI
Added verbose option to nidm_query.py
=> Added 'rest' endpoints to the nidm_query.py CLI

docker/Dockerfile, nidm/experiment/Utils.py, nidm/version.py
FuzzyWuzzy is GPLv2 licensed which would force you to licence the whole project under GPLv2. I had the same problem on one of my projects and so I wrote [rapidfuzz](https://github.com/rhasspy/rapidfuzz) which is implementing the same algorithm but is based on a version of fuzzywuzzy that was MIT Licensed and is therefor MIT Licensed aswell, so it can be used in here without forcing a License change. As a nice bonus it is fully implemented in C++ and comes with a few Algorithmic improvements making it between 5 and 100 times faster than FuzzyWuzzy.
=> use rapidfuzz instead of fuzzywuzzy

.github/workflows/pythonpublish.yml
@dbkeator - once this is merged you should not have to push releases yourself. first make a commit updating the version number and then just go to the release tab and create a new release.
=> enh: add an action to publish to pypi

nidm/experiment/Query.py, nidm/experiment/tools/rest.py, nidm/experiment/tools/tests/test_rest.py, profiler.py
This patch will look at a few different strings found in the data element definition when comparing for filters and field requests in the REST API. This means you can use things like "AGE_AT_SCAN", or the UUID for the age data element, or the isAbout URI when building the filter/fields parameters.
=> Adding support for matching synonyms when doing a filter and field match

docker-compose.yml, docker/rest-blaze.py, nidm/experiment/Navigate.py, nidm/experiment/Query.py, nidm/experiment/tests/test_query.py, nidm/experiment/tools/nidm_query.py, nidm/experiment/tools/rest.py, nidm/experiment/tools/tests/test_rest.py, nidm/experiment/tools/tests/test_rest_statistics.py, nidm/experiment/tools/tests/test_rest_subjects.py, nidm/version.py
* Loaded TTL files can be stored in Blazegraph
* Sparql query runner updated to use Blazegraph when available
* command line option --blaze to supply Blazegraph URL
* upgrade version of numpy
=> Adding support for Blazegraph

nidm/experiment/Navigate.py, nidm/version.py
Places where we are returning the full object output of variables will now include the source variable along with all the rest of the details about a value.
=> Include the source variable in the JSON return format of REST requests

nidm/experiment/Query.py, nidm/experiment/tools/rest.py, nidm/experiment/tools/tests/test_rest.py, pynidm.egg-info/requires.txt
* Now can support rest routes like:  /projects?fields=http://www.cognitiveatlas.org/ontology/cogat.owl#CAO_00962
* Fix for the issue with 'base' being included/exclude from the ilx prefix when computing project statistics.
=> Now support # in an isabout field URI

.github/workflows/pythontest.yml, nidm/experiment/Utils.py, nidm/experiment/tests/test_map_vars_to_terms.py, nidm/experiment/tools/csv2nidm.py, nidm/version.py
To align with the ReproSchema and NIDM-Terms work, these changes update the JSON mapping file structure to be consistent with those efforts.  Also a testing function was written to test both exporting the ReproSchema and NIDM-Terms format and the BIDS sidecar format if using bidsmri2nidm.  Further, the gitaction that runs pytests was changed to run on pull requests.
=> @dbkeator upgrading map_variables_to_terms to accomodate reproschema json structures

.github/workflows/pythonpublish.yml
=> Use `build` in `pythonpublish.yml`

tests/experiment/test_experiment_basic.py, tests/workflows/test_workflows.py
=> Replace `tmpdir` fixture with `tmp_path`

src/nidm/core/dot.py, src/nidm/core/serializers/__init__.py, src/nidm/core/serializers/provonerdf.py
=> Remove Python 2-specific `__future__` imports

.github/workflows/pythontest.yml, tox.ini
=> Measure test coverage

setup.cfg
Some of the packages listed as requirements were not actually in use, and there were some other packages used by pynidm that weren't listed.
Specifically:
* duecredit was unused
* graphviz (the Python project, not to be confused with actual Graphviz) was unused
* orthauth was unused
* pydotplus was unused
* python-dateutil was used but unlisted; the code only worked because it was installed by another dependency
* rdflib-jsonld has been subsumed into rdflib
* scipy was used but unlisted; the code only worked because it was installed by another dependency
* matplotlib and seaborn were unlisted, not installed by anything, and only used by a few files in `nidm/experiment/tools/`, none of which are entry points for the project; I decided to just list them as extras.
=> Clean up install requirements

setup.cfg, src/nidm/experiment/Query.py, src/nidm/experiment/tools/rest.py, src/nidm/experiment/tools/rest_statistics.py
`joblib.Memory` was imported & instantiated in a few places, but nothing was done with it.
=> Remove practically-unused `joblib`

tests/experiment/tools/test_nidm_lingreg.py
=> Clean up Click testing

docker/rest-server.py, src/nidm/core/dot.py, src/nidm/core/serializers/__init__.py, src/nidm/core/serializers/provonerdf.py, src/nidm/experiment/CDE.py, src/nidm/experiment/Core.py, src/nidm/experiment/Navigate.py, src/nidm/experiment/Query.py, src/nidm/experiment/Session.py, src/nidm/experiment/Utils.py, src/nidm/experiment/tools/bidsmri2nidm.py, src/nidm/experiment/tools/csv2nidm.py, src/nidm/experiment/tools/nidm2bids.py, src/nidm/experiment/tools/nidm_affinity_propagation.py, src/nidm/experiment/tools/nidm_linreg.py, src/nidm/experiment/tools/nidm_merge.py, src/nidm/experiment/tools/nidm_query.py, src/nidm/experiment/tools/nidm_version.py, src/nidm/experiment/tools/repronim_simple2_brainvolumes.py, src/nidm/experiment/tools/rest.py, tests/experiment/read_nidm.py, tests/experiment/termsearch.py, tests/experiment/test_query.py, tests/experiment/tools/test_rest.py, tests/experiment/tools/test_rest_dataelements.py
=> Improve string formatting syntax

src/nidm/experiment/Query.py, src/nidm/experiment/tools/bidsmri2nidm.py, src/nidm/experiment/tools/csv2nidm.py, src/nidm/experiment/tools/nidm2bids.py, src/nidm/experiment/tools/nidm_concat.py, src/nidm/experiment/tools/nidm_convert.py, src/nidm/experiment/tools/nidm_linreg.py, src/nidm/experiment/tools/nidm_merge.py, src/nidm/experiment/tools/nidm_query.py, src/nidm/experiment/tools/nidm_utils.py, src/nidm/experiment/tools/nidm_visualize.py, src/nidm/experiment/tools/repronim_simple2_brainvolumes.py
Part of #325.
@yarikoptic Question: Should the persons listed in the "Coded by" fields removed by this PR be listed in a CONTRIBUTORS file or similar?  There are only two such persons listed, David Keator and Ashmita Kumar, both of whom are already listed as authors in the Git history and as contributors on GitHub.
=> Pare down giant comment blocks that largely do what Git already does

.readthedocs.yaml, docs/requirements.txt, tox.ini
This should get the docs building again.
=> Use `.readthedocs.yaml` file to install pynidm in RTD environment

src/nidm/experiment/Query.py, src/nidm/experiment/Utils.py, src/nidm/experiment/tools/bidsmri2nidm.py, src/nidm/experiment/tools/csv2nidm.py, src/nidm/experiment/tools/nidm2bids.py, src/nidm/experiment/tools/nidm_affinity_propagation.py, src/nidm/experiment/tools/nidm_agglomerative_clustering.py, src/nidm/experiment/tools/nidm_convert.py, src/nidm/experiment/tools/nidm_gmm.py, src/nidm/experiment/tools/nidm_kmeans.py, src/nidm/experiment/tools/nidm_linreg.py, src/nidm/experiment/tools/nidm_query.py, src/nidm/experiment/tools/nidm_utils.py, src/nidm/experiment/tools/repronim_simple2_brainvolumes.py, tests/core/test_provone.py, tests/experiment/create_testfile.py, tests/experiment/read_nidm.py, tests/experiment/test_experiment.py, tests/experiment/test_experiment_basic.py, tests/experiment/test_map_vars_to_terms.py, tests/experiment/test_query.py, tests/experiment/tools/test_rest.py, tests/workflows/test_workflows.py
Calling `open()` without an explicit encoding uses the OS encoding, which is not always sensible.  See [PEP 597](https://peps.python.org/pep-0597/) et alii.
=> Open all text files with UTF-8 encoding

src/nidm/core/Constants.py, src/nidm/core/provone.py, src/nidm/core/serializers/__init__.py, src/nidm/core/serializers/provonerdf.py, src/nidm/experiment/Acquisition.py, src/nidm/experiment/Core.py, src/nidm/experiment/Derivative.py, src/nidm/experiment/Navigate.py, src/nidm/experiment/Query.py, src/nidm/experiment/Utils.py, src/nidm/experiment/tools/bidsmri2nidm.py, src/nidm/experiment/tools/csv2nidm.py, src/nidm/experiment/tools/nidm2bids.py, src/nidm/experiment/tools/nidm_affinity_propagation.py, src/nidm/experiment/tools/nidm_agglomerative_clustering.py, src/nidm/experiment/tools/nidm_gmm.py, src/nidm/experiment/tools/nidm_kmeans.py, src/nidm/experiment/tools/nidm_linreg.py, src/nidm/experiment/tools/nidm_query.py, src/nidm/experiment/tools/repronim_simple2_brainvolumes.py, src/nidm/experiment/tools/rest.py, tests/experiment/test_experiment_basic.py, tests/experiment/test_map_vars_to_terms.py, tests/experiment/test_query.py, tests/experiment/tools/test_rest.py
Part of #325.
My thanks to pylint for helping me find these.
=> Assorted minor code improvements

setup.cfg
Originally was ==1.0.5, then relaxed to be under 2.0. Current release 2.0.3 and I hope it would address some warnings
=> Allow pyld 2.x series

src/nidm/experiment/Core.py, src/nidm/experiment/Navigate.py, src/nidm/experiment/Query.py, src/nidm/experiment/tools/bidsmri2nidm.py, src/nidm/experiment/tools/rest.py, src/nidm/experiment/tools/rest_statistics.py, tests/experiment/test_experiment_basic.py, tests/experiment/tools/test_rest.py, tests/experiment/tools/test_rest_dataelements.py
Since `type` doesn't account for subclass inheritance at all, and likely in all those cases what matters is that an instance of that top level class. 
Spotted while having a pick at https://github.com/incf-nidash/PyNIDM/pull/385/files
=> Replace "type(x) is y" with "isinstance(x, y)"

src/nidm/experiment/Utils.py, src/nidm/experiment/tools/nidm_affinity_propagation.py, src/nidm/experiment/tools/nidm_agglomerative_clustering.py, src/nidm/experiment/tools/nidm_gmm.py, src/nidm/experiment/tools/nidm_kmeans.py, src/nidm/experiment/tools/nidm_linreg.py, tests/experiment/test_map_vars_to_terms.py
The map_vars_to_terms utility in pynidm was modifying json sidecar (mapping) files when they were supplied with a BIDS dataset and the user selected to do no annotations.  This is fixed along with a new test / modified tests to accommodate this change.
=> fixed bug with BIDS sidecar files when supplied by user and updated tests

src/nidm/experiment/Utils.py
IMHO a good suggestion to fix such ad-hoc "near typo" choice of a variable
=> Make PyNIDM codespell-clean again

src/nidm/experiment/Utils.py, src/nidm/experiment/tools/csv2nidm.py
Bug fixes:
- csv2nidm now adds .ttl extention to -out parameter if user didn't add it and not using an existing nidm file to add assessment data
- csv2nidm bug fixed when adding a source_url for derivative data
- pynidm annotation tools bug when trying to set the prov data type for literal values (e.g. 30, control, etc.) when those literal values haven't previously been converted to rdflib literal objects
=> fixed bug in pynidm command line annotator
